### ISSUE TITLE
clean and complete config files in romiscan/config (archive old unused versions)

### ISSUE THREAD

**Issue by fabfabBesnard** [romi/Scan3D#143]
-keep last full config files.
Annotate what's required (error if not provided) and what is optional (default if not provided, overwritten if provided)
-provide minimum "default" config files
-move other files to config/archive

**Comment by jlegrand62** [comment]
Should we use the default (minimal) TOML files for CI tests ?

**Comment by jlegrand62** [comment]
I self reply: **NO**!
The CI tests use a `test_*_pipe.toml` configuration file that contains a "specific" config for the dataset.
One important thing there seem to be the **bounding box settings**...
