### ISSUE TITLE
Allow multiple volume mounting in docker/run.sh script

### ISSUE THREAD

**Issue by fabfabBesnard** [romi/Scan3D#145]
when starting the (non-developer full-image) docker container (using docker/run.sh), allow to mount several volume with he -v option.
The behavior should be the same as the actual docker/dev/run.sh script, used for developer (pipe split into two images).

**Comment by jlegrand62** [comment]
It's done & I even fixed the missing argument '--volume' in `docker/dev/run.sh`!
Thanks.
