### ISSUE TITLE
Revert to default docker behavior

### ISSUE THREAD

**Issue by jlegrand62** [romi/Scan3D#207]
in build.sh, do not change the default behavior of docker CLI (force the Dockerfile location), change the path in GitHub action instead!

**Comment by jlegrand62** [comment]
We probably want to call `./build.sh` from the docker directory, not to have to type `./docker/build.sh`...

**Comment by jlegrand62** [comment]
If we do though, we have to fix the comments and documentation to reflect that!

**Comment by naittaleb** [comment]
We need build context.
