### ISSUE TITLE
Minor fixes for task AnglesAndInternodesEvaluation

### ISSUE THREAD

**Issue by fabfabBesnard** [romi/Scan3D#232]
Sorry that's in French !!

1. Les séquences "référence" et "test" sont inversées dans le graphe final et donc les SM sont calculé sur la référence au lieu de sur la test !
2. Dans la tableau final qui est généré, il y a un bug pour les valeurs "number chop start" etc... -> "number of merge events": ils sont tous à 0 même s'il en existe, alors que ces mêmes Split/Merge sont bien détectés dans la suite du json (missed events per split et added events per merge)
3. dans la suite du json, on a ""sequence_0 mean difference" ou "sequence_1 mean difference": le _0 et _1 c'est pour les angles et les entre-noeuds ?
4. améliorer les titres (angles/entre-noeuds au lieu de séquence_0/1)
5. changer les angles en degrés et pas en radian
6. fixer l'intervalle des angles de 0 à 360°

**Comment by jlegrand62** [comment]
> 5. changer les angles en degrés et pas en radian
C'est pour les données référence renvoyées par la tâche `VirtualScan` ?
Dans ce cas c'est plutôt cette tâche qu'il faudra corriger non ?
